name: "eg-cicd-haskell"
version: 0.8
github: "rik-howard/eg-cicd-haskell"
license: "GPL"
license-file: "etc/license"
author: "Rik Howard"
maintainer: "rik@lrbh.info"
copyright: "2024 Rik Howard"
synopsis: "EG CICD Haskell is an experiment."
category: "Experimental"
description: "Please see the read-me on GitHub at <https://github.com/rik-howard/eg-cicd-haskell>"

extra-doc-files:
- readme.md
- artisan.md
- builder.md
- changes.md

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-name-shadowing

library:
  source-dirs: src

executables:
  eg-cicd-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text >= 2.0.2 && < 2.2
    - neat-interpolation >= 0.5.1.4 && < 0.5.2
    - eg-cicd-haskell

tests:
  eg-cicd-haskell-test:
    main: Test.hs
    source-dirs: tst
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eg-cicd-haskell
    - HUnit
