name: EG CICD Haskell

on:
  push:
    tags: ["*"]

permissions:
  contents: write

jobs:
  build:
    strategy:

      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux-x86_64
          - os: macos-latest
            platform: macos-x86_64
          - os: windows-latest
            platform: windows-x86_64

    runs-on: ${{matrix.os}}

    steps:

    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Show details
      runs: ls -al

    - name: Install Stack
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.4.7'
        stack-version: 'latest'
        enable-stack: true

    - name: Show details
      runs: ls -al
