name: EG CICD Haskell

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Unpack YAML
      run: mv etc/*.yaml* .
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.4.7'
        stack-version: 'latest'
        enable-stack: true
    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-stack
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{runner.os}}-stack-${{hashFiles ('stack.yaml', 'package.yaml')}}
        restore-keys: |
          ${{runner.os}}-stack-
    - name: Install dependencies
      run: stack setup && stack build --only-dependencies
    - name: Build project
      run: stack build
    - name: Run tests
      run: stack test
    - name: Repack YAML 
      run: mv *.yaml* etc
