name: Cross-Platform Build

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux-x86_64
          #- os: macos-latest
          #  platform: macos-x86_64
          #- os: windows-latest
          #  platform: windows-x86_64

    runs-on: ${{matrix.os}}

    steps:

    - name: Check out project
      uses: actions/checkout@v4

    - name: Unpack YAML
      run: mv etc/*.yaml* .

    - name: Install Stack
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.4.7'
        stack-version: 'latest'
        enable-stack: true

    - name: Set up Stack
      run: stack setup

    - name: Build dependencies
      run: stack build --only-dependencies

    - name: Build project
      run: stack build

    - name: Run tests
      run: stack test

    - name: Review project
      run: |
        mkdir bin
        exe=$(find $(stack path --local-install-root)/bin -executable)
        pgm=${{github.event.repository.name}}
        vsn=${{github.ref_name}}
        pfm=${{matrix.platform}}
        ass=$pgm-$vsn-$pfm
        cp $exe $ass
        echo "asset=$ass" >> $GITHUB_ENV
        #ls -al
        #echo ---
        #stack path --local-install-root
        #echo --o
        #echo ${{github.event.repository.name}}
        #echo -o-
        #echo ${{github.ref_name}}
        #echo o--
        #echo ${{matrix.platform}}
        #echo ---
        #ls $(stack path --local-install-root)/bin
        #executable_path="$(stack path --local-install-root)/bin/*"
        #echo "executable_path=$executable_path" >> $GITHUB_ENV

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: ${{github.event.repository.name}}-${{github.ref_name}}-${{matrix.platform}}
        path: ${{env.asset}}
