name: Cross-Platform Build

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Check out project
      uses: actions/checkout@v4

    - name: Review project
      run: ls -al
