name: Cross-Platform Build

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]

    runs-on: ${{matrix.os}}

    steps:

    - name: Check out project
      uses: actions/checkout@v4

    - name: Unpack YAML
      run: mv etc/*.yaml* .

    - name: Install Stack
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.4.7'
        stack-version: 'latest'
        enable-stack: true

    - name: Set up Stack
      run: stack setup

    - name: Build dependencies
      run: stack build --only-dependencies

    - name: Build project
      run: stack build

    - name: Run tests
      run: stack test

    - name: Review project
      run: |
        ls -al
        ls -l .stack-work/dist/**/build/*/*

    - name: Repack YAML
      run: mv *.yaml* etc
