name: Linux X64 Build

on:
  push:
    tags: ['*']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest  # [linux, x64]
    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Unpack YAML
      run: mv etc/*.yaml* .

    - name: Install Stack
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.4.7'
        stack-version: 'latest'
        enable-stack: true

    - name: Set up Stack
      run: stack setup

    - name: Build dependencies
      run: stack build --only-dependencies

    - name: Build project
      run: stack build

    - name: Run tests
      run: stack test

    - name: Locate binary
      shell: bash
      run: |
        PGM=$(yq '.name' etc/package.yaml)                  # eg-cicd-haskell
        VSN=${{github.ref_name}}                            # v3.0
        SYS=$(uname -s  | tr '[:upper:]' '[:lower:])        # linux
        MAC=$(uname -m)                                     # x86_64
        BIN=$(stack path --local-install-root)/bin          # .stack-work/.../bin
        EXE=$(yq '.executables.[] | key' etc/package.yaml)  # eg-cicd-haskell-exe
        ART=$PGM-$VSN-$SYS-$MAC
        ls $BIN
        cp $BIN/$EXE $ART
        echo artefact=$ART >> $GITHUB_ENV;;

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: linux-x86_64
        path: ${{env.artefact}}
        if-no-files-found: error
