name: Pipeline

on:
  push:
    tags: ['*']

permissions:
  contents: write

jobs:

  build-linux-amd:
    uses: ./.github/workflows/build-linux-amd64.yaml

  release:
    needs: [build-linux-amd]
    uses: ./.github/workflows/release.yaml
    with:
      artefact_name_linux_amd: ${{needs.build-linux-x86_64.artefact_name_linux_amd}}
