name: Pipeline

on:
  push:
    tags: ['*']

permissions:
  contents: write

jobs:

  linux-amd:
    uses: ./.github/workflows/build-linux-amd.yaml

  release:
    needs: [linux-amd]
    uses: ./.github/workflows/release.yaml
    with:
      linux_amd_name: ${{needs.linux-amd.artefact_name}}
