name: Release

on:
  workflow_call:
    inputs:
      artefact_name_linux_amd:
        type: string
        required: false
        default: 'linux-amd64'
      #artefact_name_linux_arm:
      #  type: string
      #  required: false
      #  default: 'linux-arm64'
      #artefact_name_macos_amd:
      #  type: string
      #  required: false
      #  default: 'macos-amd64'
      #artefact_name_macos_arm:
      #  type: string
      #  required: false
      #  default: 'macos-arm64'
      #artefact_name_windows_amd:
      #  type: string
      #  required: false
      #  default: 'windows-amd64'
      #artefact_name_windows_arm:
      #  type: string
      #  required: false
      #  default: 'windows-arm64'

permissions:
  contents: write

jobs:

  release:

    runs-on: ubuntu-latest

    steps:

      #- name: Check out why?
      #  uses: actions/checkout@v4

      - name: Download executable Linux AMD64
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artefact_name_linux_amd}}
          path: artefacts

#      - name: Download executable MacOS AMD64
#        uses: actions/download-artifact@v4
#        with:
#          name: macos-x86_64
#          path: artefacts
#
#      - name: Download executable Windows AMD64
#        uses: actions/download-artifact@v4
#        with:
#          name: windows-x86_64
#          path: artefacts
#
#      - name: Download executable Linux ARM64
#        uses: actions/download-artifact@v4
#        with:
#          name: linux-arm64
#          path: artefacts
#
#      - name: Download executable MacOS ARM64
#        uses: actions/download-artifact@v4
#        with:
#          name: macos-arm64
#          path: artefacts
#
#      - name: Download executable Windows ARM64
#        uses: actions/download-artifact@v4
#        with:
#          name: windows-arm64
#          path: artefacts
#
#      - name: Set permissions
#        run: |
#          chmod +x artefacts/*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artefacts/*
          tag_name: ${{github.ref_name}}
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{secrets.GITHUB_TOKEN}}
