name: Release

on:
  workflow_call:
    workflows: ['Build Linux X86_64']
    tags: ['*']
    types:
    - completed

permissions:
  contents: write

jobs:

  release:

    if: ${{github.event.workflow_run.conclusion == 'success'}}

    runs-on: ubuntu-latest

    steps:

      - name: Check out why?
        uses: actions/checkout@v4

      - name: Download executable Linux x86_64
        uses: actions/download-artifact@v4
        with:
          name: linux-x86_64
          path: artefacts

#      - name: Download executable MacOS x86_64
#        uses: actions/download-artifact@v4
#        with:
#          name: macos-x86_64
#          path: artefacts
#
#      - name: Download executable Windows x86_64
#        uses: actions/download-artifact@v4
#        with:
#          name: windows-x86_64
#          path: artefacts
#
#      - name: Download executable Linux ARM64
#        uses: actions/download-artifact@v4
#        with:
#          name: linux-arm64
#          path: artefacts
#
#      - name: Download executable MacOS ARM64
#        uses: actions/download-artifact@v4
#        with:
#          name: macos-arm64
#          path: artefacts
#
#      - name: Download executable Windows ARM64
#        uses: actions/download-artifact@v4
#        with:
#          name: windows-arm64
#          path: artefacts

      - name: Set permissions
        run: |
          chmod +x artefacts/*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artefacts/*
          tag_name: ${{github.ref_name}}
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{secrets.GITHUB_TOKEN}}
